name: movieapps
version: 1.0.0+1
publish_to: none
description: Aplikasi Movie.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  empty_widget: ^0.0.5
  fancy_shimmer_image: ^2.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  get: 4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  readmore: ^2.2.0
  responsive_framework: ^0.2.0
  search_page: ^2.0.0+1
  url_launcher: ^6.1.5
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon1.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
